"""sprint_12_campaign_assets_fields

Revision ID: 0367530f5e19
Revises: 2822d8f53bb6
Create Date: 2026-07-17 18:34:13.856515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0367530f5e19'
down_revision = '2822d8f53bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_used', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('generation_time', sa.Float(), nullable=True))
        batch_op.drop_constraint(batch_op.f('campaign_assets_task_id_fkey'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_assets', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('campaign_assets_task_id_fkey'), 'workflow_tasks', ['task_id'], ['id'])
        batch_op.drop_column('generation_time')
        batch_op.drop_column('provider_used')

    # ### end Alembic commands ###
