"""Create provider health and log tables

Revision ID: 08fb6bdfb31e
Revises: 1838ba067d67
Create Date: 2026-07-16 16:13:16.014965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fb6bdfb31e'
down_revision = '1838ba067d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
