"""add monthly image tracking

Revision ID: 17735721edb5
Revises: ea67622a5e45
Create Date: 2026-05-29 22:39:26.499141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17735721edb5'
down_revision = 'ea67622a5e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_images_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_image_reset', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_image_reset')
        batch_op.drop_column('monthly_images_used')

    # ### end Alembic commands ###
