"""sprint_11_campaign_foundation

Revision ID: 2822d8f53bb6
Revises: 9e74e0539e64
Create Date: 2026-07-17 16:48:10.997341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2822d8f53bb6'
down_revision = '9e74e0539e64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('metadata', sa.Text(), nullable=True))

    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('business_goal', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('target_audience', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tone', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_column('progress')
        batch_op.drop_column('industry')
        batch_op.drop_column('tone')
        batch_op.drop_column('target_audience')
        batch_op.drop_column('business_goal')
        batch_op.drop_column('title')

    with op.batch_alter_table('campaign_assets', schema=None) as batch_op:
        batch_op.drop_column('metadata')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('file_url')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
