"""Add publishing retry queue and provider health v3

Revision ID: 35fb432cc669
Revises: 567f364073bf
Create Date: 2026-07-23 19:09:51.368542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35fb432cc669'
down_revision = '567f364073bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishing_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('response_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('published_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('execution_time_ms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('error_details', sa.Text(), nullable=True))

    with op.batch_alter_table('user_contents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('published_to', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_contents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('published_to')
        batch_op.drop_column('published_at')

    with op.batch_alter_table('publishing_logs', schema=None) as batch_op:
        batch_op.drop_column('error_details')
        batch_op.drop_column('execution_time_ms')
        batch_op.drop_column('published_url')
        batch_op.drop_column('response_id')
        batch_op.drop_column('request_id')

    # ### end Alembic commands ###
