"""add fal request id

Revision ID: 45767f11d60d
Revises: 17735721edb5
Create Date: 2026-05-31 23:05:26.050993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45767f11d60d'
down_revision = '17735721edb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fal_request_id', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.drop_column('fal_request_id')

    # ### end Alembic commands ###
