"""Add ServiceCredential

Revision ID: 6872cc1810ae
Revises: 35fb432cc669
Create Date: 2026-07-24 18:50:17.537838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6872cc1810ae'
down_revision = '35fb432cc669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
