"""add image fields to generations

Revision ID: 77cc16399cfa
Revises: e7d077b7abe8
Create Date: 2026-03-21 10:15:54.962718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cc16399cfa'
down_revision = 'e7d077b7abe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('generation_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.drop_column('generation_type')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
