"""Add Campaign workflow models

Revision ID: 9e74e0539e64
Revises: a7e17d736419
Create Date: 2026-07-16 16:53:46.591127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e74e0539e64'
down_revision = 'a7e17d736419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
