"""Actually create provider models

Revision ID: a7e17d736419
Revises: 08fb6bdfb31e
Create Date: 2026-07-16 16:14:47.273596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e17d736419'
down_revision = '08fb6bdfb31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
