"""add daily credits

Revision ID: cfda0523ca64
Revises: 77cc16399cfa
Create Date: 2026-05-17 12:15:37.268075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfda0523ca64'
down_revision = '77cc16399cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_credits_used', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_credit_reset', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_credit_reset')
        batch_op.drop_column('daily_credits_used')

    # ### end Alembic commands ###
