"""Add FacebookPostHistory

Revision ID: d3000faedf48
Revises: c3e7a1b9d2f4
Create Date: 2026-06-26 21:44:11.610328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3000faedf48'
down_revision = 'c3e7a1b9d2f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
