"""added ad_watched to generation

Revision ID: ea67622a5e45
Revises: cfda0523ca64
Create Date: 2026-05-21 21:32:27.116762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea67622a5e45'
down_revision = 'cfda0523ca64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_watched', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generations', schema=None) as batch_op:
        batch_op.drop_column('ad_watched')

    # ### end Alembic commands ###
